# Generated by Django 4.1.6 on 2023-02-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainDash', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devices',
        ),
    ]
