# Generated by Django 4.1.6 on 2023-02-27 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainDash', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='devices_id',
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=50)),
                ('datetime', models.DateField()),
                ('notes', models.CharField(max_length=50)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainDash.devices')),
            ],
        ),
    ]
