# Generated by Django 4.1.6 on 2023-02-28 21:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainDash', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=50)),
                ('devie_model', models.CharField(max_length=50)),
                ('device_serial_number', models.CharField(max_length=50)),
                ('device_qty', models.IntegerField()),
                ('device_price', models.IntegerField()),
                ('device_sellers_origin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=50)),
                ('datetime', models.DateField()),
                ('notes', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainDash.device')),
            ],
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
    ]
