# Generated by Django 4.1.6 on 2023-03-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainDash', '0004_device_record_delete_devices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_name',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_sellers_origin',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_qty',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_serial_number',
            new_name='sellers_origin',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='devie_model',
            new_name='serial_number',
        ),
    ]
