# Generated by Django 4.1.6 on 2023-02-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainDash', '0004_remove_devices_devices_id_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
