# Generated by Django 4.1.6 on 2023-03-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainDash', '0005_rename__id_device_id_rename_device_name_device_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='assigne_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='assigne_room_num',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='transaction',
            field=models.CharField(choices=[('ASSIGNEMNT', 'Assignment'), ('RETRIEVAL', 'Retrieval')], default='ASSIGNMENT', max_length=50),
        ),
    ]
