# Generated by Django 4.1.6 on 2023-03-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainDash', '0007_device_availability_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='availability_count',
            new_name='assignment_count',
        ),
    ]
